AllCops:
  TargetRubyVersion: 2.4

Eval:
  Exclude:
    - "Rakefile"
    - "**/version.rb"

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Exclude:
    - "spec/**/*"

Naming/FileName:
  Exclude:
    - "bin/*"

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SignalException:
  EnforcedStyle: semantic

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RegexpLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false
